# Generated by Django 5.2.10 on 2026-02-20 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelproductividad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='registroproductividad',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='registroproductividad',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='registroproductividad',
            name='tareas_realizadas',
        ),
        migrations.RemoveField(
            model_name='registroproductividad',
            name='telefono_cliente',
        ),
        migrations.RemoveField(
            model_name='registroproductividad',
            name='tipo_trabajo',
        ),
        migrations.RemoveField(
            model_name='registroproductividad',
            name='vehiculo_modelo',
        ),
        migrations.RemoveField(
            model_name='registroproductividad',
            name='vehiculo_placa',
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='armado',
            field=models.PositiveIntegerField(default=0, verbose_name='Armado'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='cortado',
            field=models.PositiveIntegerField(default=0, verbose_name='Cortado'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='costura',
            field=models.PositiveIntegerField(default=0, verbose_name='Costura'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='instalacion',
            field=models.PositiveIntegerField(default=0, verbose_name='Instalación'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='marcado_piezas',
            field=models.PositiveIntegerField(default=0, verbose_name='Marcado de Piezas'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='sillas_realizadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Sillas Realizadas'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='tapizado_puertas',
            field=models.PositiveIntegerField(default=0, verbose_name='Tapizado Puertas'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='tapizado_techo',
            field=models.PositiveIntegerField(default=0, verbose_name='Tapizado Techo'),
        ),
        migrations.AddField(
            model_name='registroproductividad',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='panelproductividad.trabajador', verbose_name='Trabajador'),
        ),
    ]
