# Generated by Django 6.0.2 on 2026-02-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
    ]
