# Generated by Django 6.0.2 on 2026-03-06 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0002_alter_producto_options_remove_producto_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios (Luz, Agua, Internet)'), ('alquiler', 'Alquiler / Arriendo'), ('materiales', 'Materiales e Insumos'), ('herramientas', 'Herramientas y Equipos'), ('transporte', 'Transporte'), ('salarios', 'Salarios / Nómina'), ('impuestos', 'Impuestos'), ('mantenimiento', 'Mantenimiento'), ('publicidad', 'Publicidad / Marketing'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Categoría')),
                ('fecha', models.DateField(verbose_name='Fecha del Gasto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
    ]
