# Generated by Django 4.2.29 on 2026-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0003_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_precio_variable',
            field=models.BooleanField(default=False, help_text='Si está activo, el trabajador ingresa el precio al crear la tarea', verbose_name='Precio Variable'),
        ),
    ]
