# Generated by Django 6.0.2 on 2026-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0004_producto_es_precio_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
    ]
