# Generated by Django 6.0.4 on 2026-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0005_remove_producto_categoria_delete_categoriaproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador (Acceso total)'), ('gerente', 'Gerente (Tareas, Productividad, Finanzas Básico)'), ('trabajador', 'Trabajador (Tareas y Productividad)')], default='trabajador', help_text='Define el nivel de acceso del usuario a los módulos de la aplicación', max_length=20, verbose_name='Rol'),
        ),
    ]
