# Generated by Django 6.0.4 on 2026-04-18 03:15

from django.db import migrations


def migrate_roles(apps, schema_editor):
    """
    Migra los roles del sistema antiguo (jefe/trabajador) al nuevo sistema (administrador/gerente/trabajador).
    
    Lógica:
    - 'jefe' → 'administrador' (acceso total)
    - 'trabajador' → 'trabajador' (sin cambios)
    """
    PerfilUsuario = apps.get_model('panelfinanzas', 'PerfilUsuario')
    
    # Convertir todos los usuarios con rol 'jefe' a 'administrador'
    PerfilUsuario.objects.filter(rol='jefe').update(rol='administrador')


def reverse_migrate_roles(apps, schema_editor):
    """Revierte la migración: administrador → jefe"""
    PerfilUsuario = apps.get_model('panelfinanzas', 'PerfilUsuario')
    
    # Revertir: convertir 'administrador' de vuelta a 'jefe'
    PerfilUsuario.objects.filter(rol='administrador').update(rol='jefe')


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0006_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
