# Generated by Django 5.2.10 on 2026-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0007_migrate_roles_to_new_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_bus',
            field=models.BooleanField(default=False, help_text='Si está activo, este producto aparece en el módulo de Bus', verbose_name='Producto de Bus'),
        ),
    ]
