# Generated by Django 6.0.2 on 2026-02-27 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('fortaleza', 'Fortaleza'), ('debilidad', 'Debilidad'), ('oportunidad', 'Oportunidad'), ('amenaza', 'Amenaza'), ('observacion', 'Observación General'), ('accion', 'Acción a Tomar')], default='observacion', max_length=20, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Resuelta/Atendida')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Nota de Análisis',
                'verbose_name_plural': 'Notas de Análisis',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Seleccione el primer día del mes', verbose_name='Mes')),
                ('meta_ingresos', models.DecimalField(decimal_places=2, default=0, help_text='Ingreso total esperado en el mes', max_digits=14, verbose_name='Meta de Ingresos')),
                ('meta_ganancia', models.DecimalField(decimal_places=2, default=0, help_text='Ganancia neta esperada en el mes', max_digits=14, verbose_name='Meta de Ganancia')),
                ('meta_tareas_completadas', models.PositiveIntegerField(default=0, help_text='Cantidad de tareas a completar en el mes', verbose_name='Meta de Tareas Completadas')),
                ('meta_clientes_nuevos', models.PositiveIntegerField(default=0, help_text='Cantidad de clientes nuevos esperados', verbose_name='Meta de Clientes Nuevos')),
                ('meta_items_producidos', models.PositiveIntegerField(default=0, help_text='Total de items/piezas a producir en el mes', verbose_name='Meta de Items Producidos')),
                ('notas', models.TextField(blank=True, verbose_name='Notas y Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Objetivo Mensual',
                'verbose_name_plural': 'Objetivos Mensuales',
                'ordering': ['-mes'],
                'unique_together': {('mes',)},
            },
        ),
    ]
