# Generated by Django 5.2.10 on 2026-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProductividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cliente', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('vehiculo_placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa del Vehículo')),
                ('vehiculo_modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca/Modelo')),
                ('tipo_trabajo', models.CharField(choices=[('tapizado_asientos', 'Tapizado de Asientos'), ('tapizado_puertas', 'Tapizado de Puertas'), ('tapizado_techo', 'Tapizado de Techo'), ('tapizado_tablero', 'Tapizado de Tablero'), ('tapizado_completo', 'Tapizado Completo'), ('reparacion', 'Reparación'), ('limpieza', 'Limpieza Profunda'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Trabajo')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_finalizacion', models.TimeField(verbose_name='Hora de Finalización')),
                ('tareas_realizadas', models.TextField(verbose_name='Tareas Realizadas')),
                ('empleado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empleado Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Registro de Productividad',
                'verbose_name_plural': 'Registros de Productividad',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
