# Generated by Django 4.2.29 on 2026-04-08 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panelproductividad', '0002_trabajador_remove_registroproductividad_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
