# Generated by Django 6.0.2 on 2026-04-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelproductividad', '0003_trabajador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='usuario',
        ),
    ]
