# Generated by Django 5.2.10 on 2026-02-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TareaPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa del Vehículo')),
                ('marca_vehiculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Vehículo')),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del Vehículo')),
                ('año_vehiculo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del Vehículo')),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color del Vehículo')),
                ('tipo_trabajo', models.CharField(choices=[('tapizado_asientos', 'Tapizado de Asientos'), ('tapizado_puertas', 'Tapizado de Puertas'), ('tapizado_techo', 'Tapizado de Techo'), ('tapizado_tablero', 'Tapizado de Tablero'), ('tapizado_completo', 'Tapizado Completo'), ('reparacion', 'Reparación'), ('limpieza', 'Limpieza Profunda'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Trabajo')),
                ('descripcion_trabajo', models.TextField(verbose_name='Descripción del Trabajo a Realizar')),
                ('materiales', models.TextField(verbose_name='Materiales Necesarios')),
                ('cantidad_materiales', models.CharField(max_length=200, verbose_name='Cantidad de Materiales')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridad')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Estimado')),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abono Recibido')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='paneltareas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tarea Planificada',
                'verbose_name_plural': 'Tareas Planificadas',
                'ordering': ['fecha_entrega', '-prioridad'],
            },
        ),
    ]
