# Generated by Django 5.2.10 on 2026-02-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='abono',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='año_vehiculo',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='cantidad_materiales',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='color_vehiculo',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='costo_estimado',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='marca_vehiculo',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='materiales',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='modelo_vehiculo',
        ),
        migrations.RemoveField(
            model_name='tareaplanificada',
            name='tipo_trabajo',
        ),
        migrations.AlterField(
            model_name='tareaplanificada',
            name='descripcion_trabajo',
            field=models.TextField(verbose_name='Qué se le debe hacer'),
        ),
    ]
