# Generated by Django 6.0.2 on 2026-02-22 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0002_remove_cliente_direccion_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tareas/imagenes/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='paneltareas.tareaplanificada', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Imagen de Tarea',
                'verbose_name_plural': 'Imágenes de Tareas',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
