# Generated by Django 6.0.2 on 2026-02-25 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelfinanzas', '0002_alter_producto_options_remove_producto_cantidad_and_more'),
        ('paneltareas', '0003_imagentarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaplanificada',
            name='monto_abonado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que el cliente ha abonado del precio total', max_digits=12, verbose_name='Monto Abonado'),
        ),
        migrations.CreateModel(
            name='ProductoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='panelfinanzas.producto', verbose_name='Producto')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_tarea', to='paneltareas.tareaplanificada', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Producto de Tarea',
                'verbose_name_plural': 'Productos de Tareas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
