# Generated by Django 4.2.29 on 2026-04-08 04:05

from django.db import migrations, models
import paneltareas.models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0004_tareaplanificada_monto_abonado_productotarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotarea',
            name='ajuste_precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor positivo para cobrar más, negativo para descuento', max_digits=12, verbose_name='Ajuste de Precio'),
        ),
        migrations.AlterField(
            model_name='imagentarea',
            name='imagen',
            field=models.ImageField(upload_to='tareas/imagenes/%Y/%m/', validators=[paneltareas.models.validar_imagen], verbose_name='Imagen'),
        ),
    ]
