# Generated by Django 4.2.29 on 2026-04-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0005_productotarea_ajuste_precio_alter_imagentarea_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotarea',
            name='placa',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Placa del Vehículo'),
        ),
    ]
