# Generated by Django 6.0.2 on 2026-04-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0006_productotarea_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='tareaplanificada',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa del Vehículo'),
        ),
    ]
