# Generated by Django 6.0.2 on 2026-04-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0007_cliente_direccion_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagentarea',
            name='producto_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='paneltareas.productotarea', verbose_name='Producto de la tarea'),
        ),
    ]
