# Generated by Django 6.0.4 on 2026-04-24 16:59

import paneltareas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0008_imagentarea_producto_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='imagentarea',
            name='imagen',
            field=models.ImageField(max_length=255, upload_to='tareas/imagenes/%Y/%m/', validators=[paneltareas.models.validar_imagen], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productotarea',
            name='placa',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Placa del Vehículo'),
        ),
        migrations.AlterField(
            model_name='tareaplanificada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tareaplanificada',
            name='placa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placa del Vehículo'),
        ),
        migrations.AlterField(
            model_name='tareaplanificada',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=25, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='tareaplanificada',
            name='telefono_cliente',
            field=models.CharField(max_length=255, verbose_name='Teléfono de Contacto'),
        ),
    ]
