# Generated by Django 5.2.10 on 2026-05-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0009_alter_cliente_telefono_alter_imagentarea_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotarea',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del trabajo para este producto'),
        ),
        migrations.AlterField(
            model_name='tareaplanificada',
            name='descripcion_trabajo',
            field=models.TextField(blank=True, default='', verbose_name='Qué se le debe hacer'),
        ),
    ]
