# Generated by Django 5.2.10 on 2026-05-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0010_productoTarea_descripcion_tarea_trabajo_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaplanificada',
            name='categoria',
            field=models.CharField(choices=[('taller', 'Taller'), ('bus', 'Bus')], default='taller', max_length=20, verbose_name='Categoría'),
        ),
    ]
