# Generated by Django 5.2.10 on 2026-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0011_add_categoria_to_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaplanificada',
            name='telefono_cliente',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Teléfono de Contacto'),
        ),
    ]
