# Generated by Django 5.2.10 on 2026-05-27 20:34

import paneltareas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0012_telefono_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagentarea',
            name='imagen',
            field=models.ImageField(max_length=255, upload_to='tareas/%Y/%m/', validators=[paneltareas.models.validar_imagen], verbose_name='Imagen'),
        ),
    ]
