# Generated by Django 5.2.10 on 2026-06-29 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0012_telefono_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagentarea',
            name='eliminada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='En papelera'),
        ),
        migrations.AddField(
            model_name='imagentarea',
            name='eliminada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.CreateModel(
            name='NotaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tomada', models.BooleanField(default=False, verbose_name='Nota tomada')),
                ('tomada_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se tomó')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Nota de Trabajo',
                'verbose_name_plural': 'Notas de Trabajo',
                'ordering': ['-creado_en'],
            },
        ),
    ]
