# Generated by Django 5.2.10 on 2026-06-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneltareas', '0013_alter_imagentarea_imagen'),
        ('paneltareas', '0013_imagentarea_eliminada_imagentarea_eliminada_en_and_more'),
    ]

    operations = [
    ]
